name: Preprocessing Dataset

on: 
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Install dependecies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy scikit-learn

    - name: Run preprocessing script
      run: |
        python preprocessing/automate_Valeriant.py

    - name: Commit processed dataset
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add preprocessing/dataset_preprocessing/*
        git commit -m "Update processed dataset [skip ci]" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Valenttanda/Eksperimen_SML_Valeriant.git HEAD:main